services:
   nham:
    image: postgres:latest
    container_name: test_wtc
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: teste
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: